# MÓDULO 10: DOCKER - HOLA DOCKER
# ==========================================
# TODO: 1. Elegir una imagen base minimalista como `alpine`.
# TODO: 2. Definir el comando por defecto para imprimir el mensaje "Hola Docker" usando echo.

# ¡Comienza tu Dockerfile aquí!