name: 04 - Events

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]


jobs:
  inspect-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Inspect event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Event: ${{ github.event.issue.number }}"
          echo "Event: ${{ github.event.comment.body }}"