name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Lint
        run: |
          cd 09-ci-cd
          echo "::group::Lint"
          pnpm lint:frontend
          echo "::endgroup::"
  frontend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test
        run: |
          cd 09-ci-cd
          echo "::group::Test"
          pnpm test:frontend
          echo "::endgroup::"
  frontend-build:
    needs: [frontend-lint, frontend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Build
        run: |
          cd 09-ci-cd
          echo "::group::Build"
          pnpm build:frontend
          echo "::endgroup::"
  backend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Lint
        run: |
          cd 09-ci-cd
          echo "::group::Lint"
          pnpm lint:backend
          echo "::endgroup::"
  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test
        run: |
          cd 09-ci-cd
          echo "::group::Test"
          pnpm test:backend
          echo "::endgroup::"
  backend-smoke-test:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Smoke test
        run: |
          cd 09-ci-cd
          echo "::group::Smoke test"
          pnpm build:backend
          pnpm start:backend &
          sleep 3
          curl -X GET http://localhost:3000/health
          echo "::endgroup::"